### ISSUE TITLE
Sample starts with exception.Could pls kindly help how to fix?..

### ISSUE THREAD

**Issue by KyleXY1985** [spring-cloud-incubator/spring-cloud-etcd#41]
2017-03-14 14:49:22.471  WARN 3916 --- [           main] o.s.c.etcd.config.EtcdPropertySource     : Unable to init property source: config/testEtcdApp

java.io.IOException: null
	at mousio.etcd4j.promises.EtcdResponsePromise.get(EtcdResponsePromise.java:55) ~[etcd4j-2.7.0.jar:na]
	at org.springframework.cloud.etcd.config.EtcdPropertySource.init(EtcdPropertySource.java:60) ~[classes/:na]
	at org.springframework.cloud.etcd.config.EtcdPropertySourceLocator.locate(EtcdPropertySourceLocator.java:63) [classes/:na]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:89) [spring-cloud-context-1.1.0.BUILD-SNAPSHOT.jar:1.1.0.BUILD-SNAPSHOT]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:611) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:348) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1162) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1151) [spring-boot-1.5.2.RELEASE.jar:1.5.2.RELEASE]
	at org.springframework.cloud.etcd.sample.SampleEtcdApplication.main(SampleEtcdApplication.java:84) [classes/:na]

**Comment by bbruun** [comment]
I second that - having optedto use an already existing etcd (test) cluster and changing the URL in spring-cloud-etcd-core/src/main/java/org/springframework/cloud/etcd/EtcdProperties.java to the new path I get the same error.
`$ java -jar spring-cloud-etcd-sample/target/spring-cloud-etcd-sample-1.0.0.BUILD-SNAPSHOT.jar 
2017-05-22 13:10:16.450  INFO 16981 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@4919860e: startup date [Mon May 22 13:10:16 CEST 2017]; root of context hierarchy
2017-05-22 13:10:16.695  INFO 16981 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-05-22 13:10:16.753  INFO 16981 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'configurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$4021b467] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-05-22 13:10:16.936  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:16.940  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:16.941  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:17.011  INFO 16981 --- [           main] mousio.etcd4j.transport.EtcdNettyClient  : Setting up Etcd4j Netty client
2017-05-22 13:10:17.163  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:17.163  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:17.163  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:17.165  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:17.165  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.
2017-05-22 13:10:17.165  WARN 16981 --- [           main] figurationPropertiesBindingPostProcessor : The @ConfigurationProperties bean class org.springframework.cloud.etcd.EtcdProperties contains validation constraints but had not been annotated with @Validated.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.2.RELEASE)

2017-05-22 13:10:38.110  WARN 16981 --- [           main] o.s.c.etcd.config.EtcdPropertySource     : Unable to init property source: config/testEtcdApp

mousio.client.exceptions.PrematureDisconnectException: null
        at mousio.etcd4j.transport.AbstractEtcdResponseHandler.channelUnregistered(AbstractEtcdResponseHandler.java:48) ~[etcd4j-2.7.0.jar!/:na]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelUnregisteredNow(ChannelHandlerInvokerUtil.java:40) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelUnregistered(DefaultChannelHandlerInvoker.java:64) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:121) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelUnregisteredNow(ChannelHandlerInvokerUtil.java:40) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelUnregistered(DefaultChannelHandlerInvoker.java:64) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:121) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelUnregisteredNow(ChannelHandlerInvokerUtil.java:40) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelUnregistered(DefaultChannelHandlerInvoker.java:64) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:121) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelUnregisteredNow(ChannelHandlerInvokerUtil.java:40) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelUnregistered(DefaultChannelHandlerInvoker.java:64) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:121) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelUnregistered(ChannelInboundHandlerAdapter.java:53) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelUnregisteredNow(ChannelHandlerInvokerUtil.java:40) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelUnregistered(DefaultChannelHandlerInvoker.java:64) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelUnregistered(AbstractChannelHandlerContext.java:121) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:839) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:696) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:322) ~[netty-common-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:356) ~[netty-transport-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:703) ~[netty-common-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[netty-common-4.1.0.Beta5.jar!/:4.1.0.Beta5]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.7.0_79]

`

**Comment by spencergibb** [comment]
@bbruun your stack trace is unreleated.
